config/routes.rb
Musicapp::Application.routes.draw do
  resources :notes

  resources :bands

  resources :albums

  resources :tracks

  resources :users
  root to: 'bands#index'
  post 'login', to: 'users#do_login', as: :do_login
  get 'login', to: 'users#login', as: :login
  post 'logout', to: 'users#logout'
  get 'verify.:activate_token', to: 'users#verify', as: :verify
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  lyrics     :text
#  kind       :string(255)
#  album_id   :integer
#  created_at :datetime
#  updated_at :datetime
#  title      :string(255)      not null
#

class Track < ActiveRecord::Base
  validates :lyrics, :kind, :album_id, :title, presence: true

  belongs_to :album
  has_one :band, through: :album
  has_many :notes
  has_many :tracks, through: :album
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all.includes(:album)
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track.album, notice: 'Track was successfully created.' }
        format.json { render action: 'show', status: :created, location: @track }
      else
        format.html { render action: 'new' }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track.album, notice: 'Track was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
      session[:default_track_id] = @track.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:lyrics, :kind, :album_id, :title)
    end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_disp.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Kind</th>
    </tr>
  </thead>

  <tbody>
    <% tracks.each do |track| %>
      <tr>
        <td><%= track.title %></td>
        <td><%= track.kind %></td>
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Edit', edit_track_path(track) %></td>
        <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

app/views/tracks/_form.html.erb
<%= form_for(@track) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lyrics %><br>
    <%= f.text_area :lyrics %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title%>
  <div class="field">
    <%= f.select(
    "album_id",
    Album.find(session[:default_album_id]).albums
    .sort_by{ |a| a.band.name }
    .map { |a| ["#{a.band.name}, #{a.name}", a.id] },
    selected: session[:default_album_id]
    ) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', :back %>

app/views/tracks/index.html.erb
<h1>Listing tracks</h1>

<table>
  <thead>
    <tr>
      <th>Lyrics</th>
      <th>Kind</th>
      <th>Album</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= track.lyrics %></td>
        <td><%= track.kind %></td>
        <td><%= track.album.name %></td>
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Edit', edit_track_path(track) %></td>
        <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Track', new_track_path %>

app/views/tracks/new.html.erb
<h1>New track</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @track.title %>
</p>

<p>
  <strong>Lyrics:</strong>
  <%= @track.lyrics %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @track.kind %>
</p>

<p>
  <strong>Album:</strong>
  <%= @track.album.name %>
</p>

<p>
  <strong>Band:</strong>
  <%= @track.band.name %>
</p>

<p>
  <strong>Notes:</strong>
  <%= render 'notes/disp', notes: @track.notes %>
</p>

<p>
  <%= link_to 'New Note', new_note_url%>
</p>

<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', :back %>