config/routes.rb
Musicapp::Application.routes.draw do
  resources :notes

  resources :bands

  resources :albums

  resources :tracks

  resources :users
  root to: 'bands#index'
  post 'login', to: 'users#do_login', as: :do_login
  get 'login', to: 'users#login', as: :login
  post 'logout', to: 'users#logout'
  get 'verify.:activate_token', to: 'users#verify', as: :verify
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#  activated       :boolean          default(FALSE)
#  activate_token  :string(255)
#

class User < ActiveRecord::Base
  validates :email, :password_digest, :activate_token, :session_token, presence: true
  validates :session_token, uniqueness: true
  before_validation :ensure_session_token
  before_validation :make_activate_token

  has_many :notes

  def make_activate_token
    self.activate_token ||= SecureRandom.hex
  end

  def make_session_token!
    self.session_token = SecureRandom.hex
    self.save!
  end

  def self.activate(token)
    User.find_by(activate_token: token).update!(activated: true)
  end

  def self.authenticate(params)
    user = User.find_by_email(params[:email])
    return user if user.try(:is_password?, params[:password])
    nil
  end

  def self.from_session(token)
    self.find_by_session_token(token)
  end

  def password
    nil
  end

  def ensure_session_token
    self.session_token = SecureRandom.hex if self.session_token.nil?
  end

  def password=(plaintext)
    @password = plaintext
    self.password_digest = BCrypt::Password.create(plaintext)
    nil
  end

  def is_password?(plaintext)
    BCrypt::Password.new(password_digest).is_password?(plaintext)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # GET /login
  def login
    @user = User.new
  end

  # POST /login
  def do_login
    @user = User.authenticate(user_params)
    if @user
      login!(@user)
      redirect_to root_url
    else
      flash[:errors] = 'incorrect username or password'
      redirect_to root_url
    end

  end

  def logout
    super
    redirect_to root_url
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.make_session_token!

    respond_to do |format|
      if @user.save
        login!(@user)
        UserMailer.activate_email(@user).deliver!
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  def verify
    User.activate(params[:activate_token])
    redirect_to root_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.from_session(session[:session_token])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', :back %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<h1>Log in</h1>

<%= form_for(@user, url: do_login_url) do |f| %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>

  <div class="actions">
    <%= button_to 'log in', do_login_url %>
  </div>

<% end %>

<%= link_to 'Back', :back %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', :back %>